package com.project.miaosha.dao;

import com.project.miaosha.dataobject.SequenceDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 08 16:46:23 CST 2022
     */
    int deleteByPrimaryKey(String name);
    SequenceDO getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 08 16:46:23 CST 2022
     */
    int insert(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 08 16:46:23 CST 2022
     */
    int insertSelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 08 16:46:23 CST 2022
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 08 16:46:23 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 08 16:46:23 CST 2022
     */
    int updateByPrimaryKey(SequenceDO row);
}